
defaultEntryPoints = ["http"]

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8080"

debug=true
logLevel = "DEBUG"

[traefikLog]
filePath = "tl.txt"

[accessLog]
filePath = "al.txt"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://rtr.pressler.com:9999"
    hostname = "blog.pressler.com"

  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://rtr.pressler.com:9999"
    hostname = "sv.pressler.com"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true
    [frontends.frontend1.routes.test_1]
    rule = "Host:blog.pressler.com"

  [frontends.frontend2]
  backend = "backend2"
  passHostHeader = true
    [frontends.frontend2.routes.test_1]
    rule = "Host:sv.pressler.com"