

defaultEntryPoints = ["http"]

debug=true
logLevel = "DEBUG"

[traefikLog]
filePath = "tl.txt"

[accessLog]
filePath = "al.txt"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://rtr.pressler.com:9999"


[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:vps.pressler.com"